Repository CSE-110-Group-13/cse110-sp24-group13, pull requests merged in 2024-06, with the labels that each got.

#75 update backend to include new attributes for a project object and modify the projectList attribute of a note object
  .github/workflows/main.yml
  source/.babelrc
  source/__global__.js
  source/__tests__/__mocks__/index.js
  source/__tests__/backend/NoteTable.test.js
  source/__tests__/backend/ProjectTable.test.js
  source/__tests__/backend/TaskTable.test.js
  source/__tests__/backend/generateID.test.js
  source/__tests__/calendar.test.js
  source/__tests__/calendarPage.test.js
  source/__tests__/endToEnd.test.js
  source/__tests__/favoritesPage.test.js
  source/__tests__/homePage.test.js
  source/__tests__/index.test.js
  source/__tests__/libraryPage.test.js
  source/__tests__/markdownPage.test.js
  source/__tests__/note.test.js
  source/__tests__/project.test.js
  source/__tests__/settingsPage.test.js
  source/__tests__/task.test.js
  source/backend/(sample)/note.html
  source/backend/(sample)/note.js
  source/backend/NoteTable.js
  source/backend/ProjectTable.js
  source/backend/TaskTable.js
  source/backend/index.js
  source/calendar/calendar.html
  source/homepage/index.html
  source/library/library.html
  source/markdown/markdown.html
  source/package-lock.json
  source/package.json
  source/settings/settings.html
  source/zOLD FILES/__test__/calendar.test.js
  source/zOLD FILES/__test__/devJournalApp.test.js
  source/zOLD FILES/helper-functions.js
  source/zOLD FILES/jest-puppeteer.config.js
  source/zOLD FILES/package-lock.json
  source/zOLD FILES/package.json
  source/zOLD FILES/public/calendar/calendar.html
  source/zOLD FILES/public/calendar/calendar.js
  source/zOLD FILES/public/index.html
  source/zOLD FILES/public/index.js
  source/zOLD FILES/server.js
Labels: bug, features, backend

#80 Add calendar v2
  source/calendar/calendar.css
  source/calendar/calendar.html
  source/calendar/calendar.js
Labels: features, html page

#78 Add new button styling
  .DS_Store
  source/.DS_Store
  source/addNewbutton/.DS_Store
  source/addNewbutton/addNew.js
  source/addNewbutton/addNew.svg
  source/addNewbutton/addNewold.js
  source/addNewbutton/addNote.svg
  source/addNewbutton/addProj.svg
  source/addNewbutton/back.svg
Labels: bug, enhancement, help wanted

#76 Finalized Project List HTML page. Added styling and integrated localStorage functionality
  source/backend/TaskTable.js
  source/projectlist/projectlist.css
Labels: features, html page

#117 Project list now links to view-project, added favicon and changed title for each html page
  source/calendar/calendar.html
  source/favorites/favorites.html
  source/homepage/index.html
  source/images/favicon.ico
  source/library/library.html
  source/markdown/markdown.html
  source/note/edit-note.html
  source/note/view-note.html
  source/project/edit-project.html
  source/project/view-project.html
  source/projectlist/projectTableGenerate.js
  source/projectlist/projectlist.css
  source/projectlist/projectlist.html
  source/projectlist/projectlist.js
  source/settings/settings.html
  source/verticalnavbar/verticalnavbar.html
Labels: features, html page

#121 Set default value for priority and project and some save button styling
  source/backend/ProjectTable.js
  source/project/editProject.js
  source/savecanceleditdeletebuttons/save.js
Labels: bug

#120 Made project element clickable
  source/favorites/createProject.js
  source/favorites/favorites.css
  source/favorites/project.css
  source/homepage/createProject.js
  source/homepage/project.css
Labels: features

#140 unit tests for various pages
  source/__tests__/calendarPage.test.js
  source/__tests__/favoritesPage.test.js
  source/__tests__/homePage.test.js
  source/__tests__/libraryPage.test.js
  source/__tests__/markdownPage.test.js
  source/__tests__/note.test.js
  source/__tests__/project.test.js
  source/__tests__/settingsPage.test.js
  source/__tests__/task.test.js
Labels: testing

#146 Various bug fixes
  source/calendar/calendar.html
  source/calendar/calendar.js
  source/favorites/createProject.js
  source/favorites/favorites.js
  source/homepage/createProject.js
  source/homepage/index.html
  source/homepage/index.js
  source/library/library.js
  source/note/edit-note.html
  source/note/editNote.js
  source/project/editProject.js
  source/projectinnote/projectInNote.js
  source/projectlist/projectTableGenerate.js
  source/projectlist/projectlist.js
Labels: bug

#159 Testing and global cleanup/commenting of all code
  source/__tests__/projectlistPage.test.js
  source/__tests__/unitTests.js
  source/backend/NoteTable.js
  source/backend/ProjectTable.js
  source/backend/TaskTable.js
  source/backend/index.js
  source/calendar/calendar.css
  source/calendar/calendar.html
  source/calendar/calendar.js
  source/favorites/favorites.css
  source/favorites/favorites.html
  source/favorites/favorites.js
  source/homepage/createProject.js
  source/homepage/index.css
  source/homepage/index.js
  source/homepage/noteMain.css
  source/library/NoteTable.js
  source/library/library.css
  source/library/library.js
  source/markdown/markdown.css
  source/markdown/markdown.js
  source/note/edit-note.html
  source/note/editNote.js
  source/note/notes.css
  source/note/view-note.html
  source/note/viewNote.js
  source/package.json
  source/project/edit-project.html
  source/project/editProject.js
  source/project/project.css
  source/project/view-project.html
  source/project/viewProject.js
  source/projectinnote/projectInNote.js
  source/projectlist/projectTableGenerate.js
  source/projectlist/projectlist.css
  source/projectlist/projectlist.html
  source/projectlist/projectlist.js
  source/savecanceleditdeletebuttons/cancel.js
  source/savecanceleditdeletebuttons/delete.js
  source/savecanceleditdeletebuttons/edit.js
  source/savecanceleditdeletebuttons/save.js
  source/settings/settings.css
  source/settings/settings.html
  source/settings/settings.js
  source/verticalnavbar/verticalnavbar.css
  source/verticalnavbar/verticalnavbar.html
  source/verticalnavbar/verticalnavbar.js
Labels: documentation

#161 unit tests for project and note
  source/__tests__/__mocks__/index.js
  source/__tests__/note.test.js
  source/__tests__/project.test.js
Labels: testing

#167 attempting to fix noteid bug
  source/note/edit-note.html
Labels: bug

#168 Fixing noteid bug
  source/note/edit-note.html
  source/note/editNote.js
  source/projectinnote/projectInNote.js
Labels: bug

#170 wrote unit tests and E2E test for project list
  source/__tests__/projectlistPage.test.js
  source/__tests__/unitTests.js
  source/favorites/favorites.js
  source/homepage/index.js
  source/library/library.js
  source/package.json
Labels: html page, testing
